In [39]:
import numpy as np
import pandas as pd
from scipy import misc
import matplotlib.pyplot as plt

In [3]:
## 2) Crear un vector de ceros de tamaño 10
arreglo_de_ceros = np.zeros(10)
arreglo_de_ceros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
arreglo_de_ceros_con_cinco = np.zeros(10)
arreglo_de_ceros_con_cinco[5]=1
arreglo_de_ceros_con_cinco

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [150]:
## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.
vector_cincuenta_elementos=np.arange(50)
np.argsort(vector_cincuenta_elementos)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int64)

In [21]:
## 5) Crear una matriz de 3 x 3 con valores del cero al 8
matriz_tres_por_tres = np.arange(9).reshape(3,3)
matriz_tres_por_tres

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
## 6) Encontrar los indices que no sean cero en un arreglo

arreglo_numeros=np.arange(6)
print(arreglo_numeros)
indice_que_no_sea_cero = arreglo_numeros > 0
print(indice_que_no_sea_cero)

[0 1 2 3 4 5]
[False  True  True  True  True  True]


In [29]:
## 7) Crear una matriz de identidad 3 x 3 
matriz_identidad= np.ones(9).reshape(3,3)
matriz_identidad

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
## 8) Crear una matriz 3 x 3 x 3 con valores randomicos
matriz_random = np.random.rand(3,3,3)
matriz_random

array([[[0.20735239, 0.46146607, 0.32328409],
        [0.64382659, 0.81401005, 0.52882921],
        [0.75141956, 0.54790041, 0.24470379]],

       [[0.89080483, 0.17307083, 0.43731571],
        [0.73132688, 0.87634113, 0.5695133 ],
        [0.13348904, 0.25393769, 0.48565618]],

       [[0.77496181, 0.02577165, 0.81874542],
        [0.87658085, 0.4584552 , 0.93746444],
        [0.9618125 , 0.29087124, 0.62334156]]])

In [35]:

## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor
matriz_diez = np.random.rand(10,10)
print(matriz_diez.max())
print(matriz_diez.min())


0.999896132976401
0.005833658701299038


In [42]:
## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)
imagen = misc.face() 
imagen

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [54]:
## 11) ¿Como crear una serie de una lista, diccionario o arreglo?
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

serie_lista = pd.Series(mylist)
serie_arreglo = pd.Series(myarr)
serie_diccionario =pd.Series(mydict)
print(serie_lista)
print(serie_arreglo)
print(serie_diccionario)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [174]:
## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice
df_de_la_series = pd.DataFrame(ser, index=ser.index)
df_de_la_series

0
a   0
b   1
c   2
e   3
d   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25

In [71]:
## 13) ¿Como combinar varias series para hacer un DataFrame?

ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

new_df = pd.concat((ser1, ser2), axis=1) 
new_df

0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [185]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
arreglo_val = ser1.values
arreglo_val2 = ser2.values
for i in np.nditer(arreglo_val):
    if(i not in arreglo_val2):
        print(i)

1
2
3


In [189]:
## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?

ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

arreglo_1 = ser1.values
arreglo_2 = ser1.values

for i in np.nditer(arreglo_1):
    if(i in arreglo_2):
        print(i)

1
2
3
4
5


In [118]:
## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

df = pd.DataFrame(ser)
df[0].value_counts()

a    6
g    5
h    5
f    5
e    3
d    3
b    2
c    1
Name: 0, dtype: int64

In [132]:
## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?


np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

df = pd.DataFrame(ser)
valores_repetidos = df[0].value_counts()
print(valores_repetidos)
dos_mas_repetidos = valores_repetidos.head(2)
dos_mas_repetidos = 0
dos_mas_repetidos

4    5
2    5
3    1
1    1
Name: 0, dtype: int64


0

In [142]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

ser = pd.Series(np.random.randint(1, 10, 35))
arreglo_valores = ser.values
arreglo_valores.shape
arreglo_valores.reshape(7,5)
#shape(7,5)

array([[5, 3, 1, 5, 9],
       [2, 4, 1, 9, 3],
       [9, 3, 8, 2, 3],
       [7, 2, 4, 5, 2],
       [3, 8, 3, 4, 8],
       [4, 3, 5, 9, 6],
       [6, 9, 3, 7, 8]])

In [145]:
## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?

ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u

arreglo_valores = ser.values
arreglo_valores[pos]

array(['a', 'e', 'i', 'o', 'u'], dtype=object)

In [160]:
## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

concatenar = pd.concat([ser1, ser2], axis= 1)
print(concatenar)

concatenar_dos = pd.concat([ser1, ser2], axis= 0)
print(concatenar_dos)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object


In [161]:
## 21)¿Obtener la media de una serie agrupada por otra serie?

frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'banana', 'banana', 'banana', 'manzana', 'banana', 'manzana', 'zanahoria', 'zanahoria', 'zanahoria']


In [168]:
concatenar_frutas = pd.concat([frutas, pesos], axis= 1)
concatenar_frutas

0     1
0    manzana   1.0
1     banana   2.0
2     banana   3.0
3     banana   4.0
4    manzana   5.0
5     banana   6.0
6    manzana   7.0
7  zanahoria   8.0
8  zanahoria   9.0
9  zanahoria  10.0

In [169]:
np.mean(concatenar_frutas[1])

5.5